[project]
name = "voicevox-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.10"
dependencies = [
    "aiofiles>=24.1.0",
    "anyio>=4.5.2",
    "appdirs>=1.4.4",
    "asgiref>=3.8.1",
    "certifi>=2025.7.14",
    "cffi>=1.17.1",
    "charset-normalizer>=3.4.2",
    "click>=8.1.8",
    "colorama>=0.4.6",
    "cython==0.29.24",
    "fastapi>=0.116.1",
    "h11>=0.16.0",
    "idna>=3.10",
    "jinja2>=3.1.6",
    "markupsafe>=2.1.5",
    "numpy>=1.24.4",
    "poetry>=1.8.5",
    "pycparser>=2.22",
    "pydantic>=2.10.6",
    "pyopenjtalk",
    "python-multipart>=0.0.20",
    "pyworld==0.3.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "scipy>=1.10.1",
    "setuptools>=75.3.2",
    "six>=1.17.0",
    "sniffio>=1.3.1",
    "soundfile>=0.13.1",
    "starlette>=0.44.0",
    "tqdm>=4.67.1",
    "typing-extensions>=4.13.2",
    "urllib3>=2.2.3",
    "uvicorn>=0.33.0",
]

[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = false    # TODO: eliminate errors and enable at CI
mypy_preset = "entry"  # TODO: "strict"
line_length = 88
py_version = "py38"
isort_known_first_party = ["voicevox_engine"]
isort_known_third_party = ["numpy"]
[[tool.pysen.lint.mypy_targets]]
  paths = [".", "voicevox_engine/"]

[tool.black] # automatically generated by pysen
line-length = 88
target-version = ["py38"]


[tool.isort] # automatically generated by pysen
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
known_first_party = ["voicevox_engine"]
known_third_party = ["numpy"]
line_length = 88
multi_line_output = 3
use_parentheses = true

[tool.poetry]
name = "voicevox_engine"
version = "0.0.0"
description = ""
authors = ["Hiroshiba <hihokaruta@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "^1.20.0"
fastapi = "^0.70.0"
python-multipart = "^0.0.5"
uvicorn = "^0.15.0"
aiofiles = "^0.7.0"
soundfile = "^0.10.3.post1"
scipy = "^1.7.1"
pyyaml = "^6.0"
pyworld = "^0.3.0"
appdirs = "^1.4.4"
requests = "^2.28.1"
jinja2 = "^3.1.2"
pyopenjtalk = {git = "https://github.com/VOICEVOX/pyopenjtalk", rev = "f4ade29ef9a4f43d8605103cb5bacc29e0b2ccae"}

[tool.poetry.group.dev.dependencies]
cython = "^0.29.24"
pyinstaller = "^5.3"
pre-commit = "^2.16.0"
atomicwrites = "^1.4.0"
colorama = "^0.4.4"
poetry = "^1.3.1"

[tool.poetry.group.test.dependencies]
pysen = {version = "~0", extras = ["lint"]}
pytest = "^6.2.5"
coveralls = "^3.2.0"

[tool.poetry.group.license.dependencies]
pip-licenses = "^3.5.3"

[tool.uv.sources]
pyopenjtalk = { git = "https://github.com/VOICEVOX/pyopenjtalk", rev = "f4ade29ef9a4f43d8605103cb5bacc29e0b2ccae" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
